build_image:
  stage: build
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services: 
    - name: docker:20.10.16-dind 
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - export AWS_ACCESS_KEY_ID=$REGISTRY_ID
    - export AWS_SECRET_ACCESS_KEY=$REGISTRY_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    
  script:
    - docker build -t $REGISTRY_URI/$APP_NAME:$CI_PIPELINE_IID .
    - aws ecr get-login-password | docker login --username AWS --password-stdin $REGISTRY_URI
    - docker push $REGISTRY_URI/$APP_NAME:$CI_PIPELINE_IID
